pkg load symbolic;
syms x y;
A = 1;
b = 8;
f1 = 10;
f2 = b*sqrt(y);
f(x,y) = (f1 - f2)/A;
step = 0.2;
y_init = 0;
y_euler_1 = forward_euler_method(function_handle(f(x,y)), y_init, 1.2, 0, 0.1);
y_euler_2 = forward_euler_method(function_handle(f(x,y)), y_init, 1.2, 0, step);
y_improved_euler = improved_euler_method(function_handle(f(x,y)), y_init, 1.2, 0, step);
y_runge_kutta = fourthOrder_RK_method(function_handle(f(x,y)), y_init, 1.2, 0, step);

x_vals_1 = 0: 0.1: 1.2;
x_vals_2 = 0: 0.2: 1.2;
disp(x_vals_1);
hold on;
plot(x_vals_1, y_euler_1,'r');
plot(x_vals_2, y_euler_2,'c');
plot(x_vals_2, y_improved_euler,'g');
plot(x_vals_2, y_runge_kutta,'b');
title('Variation of Height - h(t) vs. Time - t');
xlabel('Time - t'); 
ylabel('Height - h(t)'); 
legend('Forward Euler Method (h = 0.1)','Forward Euler Method (h = 0.2)',  'Improved Euler Method (h = 0.2)','4th Order Runge-Kutta Method (h = 0.2)');
